// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package io.playpen.core.protocol;

public final class Protocol {
  private Protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AuthenticatedMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.playpen.core.protocol.AuthenticatedMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string uuid = 1;</code>
     */
    boolean hasUuid();
    /**
     * <code>required string uuid = 1;</code>
     */
    java.lang.String getUuid();
    /**
     * <code>required string uuid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>required uint32 version = 4;</code>
     *
     * <pre>
     * VERSION IS SET IN io.playpen.core.Bootstrap
     * </pre>
     */
    boolean hasVersion();
    /**
     * <code>required uint32 version = 4;</code>
     *
     * <pre>
     * VERSION IS SET IN io.playpen.core.Bootstrap
     * </pre>
     */
    int getVersion();

    /**
     * <code>required string hash = 2;</code>
     */
    boolean hasHash();
    /**
     * <code>required string hash = 2;</code>
     */
    java.lang.String getHash();
    /**
     * <code>required string hash = 2;</code>
     */
    com.google.protobuf.ByteString
        getHashBytes();

    /**
     * <code>required bytes payload = 3;</code>
     */
    boolean hasPayload();
    /**
     * <code>required bytes payload = 3;</code>
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * Protobuf type {@code io.playpen.core.protocol.AuthenticatedMessage}
   */
  public static final class AuthenticatedMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:io.playpen.core.protocol.AuthenticatedMessage)
      AuthenticatedMessageOrBuilder {
    // Use AuthenticatedMessage.newBuilder() to construct.
    private AuthenticatedMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AuthenticatedMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AuthenticatedMessage defaultInstance;
    public static AuthenticatedMessage getDefaultInstance() {
      return defaultInstance;
    }

    public AuthenticatedMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AuthenticatedMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              uuid_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              hash_ = bs;
              break;
            }
            case 26: {
              bitField0_ |= 0x00000008;
              payload_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000002;
              version_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.playpen.core.protocol.Protocol.internal_static_io_playpen_core_protocol_AuthenticatedMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.playpen.core.protocol.Protocol.internal_static_io_playpen_core_protocol_AuthenticatedMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.playpen.core.protocol.Protocol.AuthenticatedMessage.class, io.playpen.core.protocol.Protocol.AuthenticatedMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<AuthenticatedMessage> PARSER =
        new com.google.protobuf.AbstractParser<AuthenticatedMessage>() {
      public AuthenticatedMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AuthenticatedMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AuthenticatedMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int UUID_FIELD_NUMBER = 1;
    private java.lang.Object uuid_;
    /**
     * <code>required string uuid = 1;</code>
     */
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string uuid = 1;</code>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uuid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string uuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 4;
    private int version_;
    /**
     * <code>required uint32 version = 4;</code>
     *
     * <pre>
     * VERSION IS SET IN io.playpen.core.Bootstrap
     * </pre>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 version = 4;</code>
     *
     * <pre>
     * VERSION IS SET IN io.playpen.core.Bootstrap
     * </pre>
     */
    public int getVersion() {
      return version_;
    }

    public static final int HASH_FIELD_NUMBER = 2;
    private java.lang.Object hash_;
    /**
     * <code>required string hash = 2;</code>
     */
    public boolean hasHash() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string hash = 2;</code>
     */
    public java.lang.String getHash() {
      java.lang.Object ref = hash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          hash_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string hash = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHashBytes() {
      java.lang.Object ref = hash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYLOAD_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>required bytes payload = 3;</code>
     */
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes payload = 3;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private void initFields() {
      uuid_ = "";
      version_ = 0;
      hash_ = "";
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHash()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPayload()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUuidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(2, getHashBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(3, payload_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(4, version_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUuidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getHashBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, payload_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, version_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.playpen.core.protocol.Protocol.AuthenticatedMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.playpen.core.protocol.Protocol.AuthenticatedMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.playpen.core.protocol.Protocol.AuthenticatedMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.playpen.core.protocol.Protocol.AuthenticatedMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.playpen.core.protocol.Protocol.AuthenticatedMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.playpen.core.protocol.Protocol.AuthenticatedMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.playpen.core.protocol.Protocol.AuthenticatedMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.playpen.core.protocol.Protocol.AuthenticatedMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.playpen.core.protocol.Protocol.AuthenticatedMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.playpen.core.protocol.Protocol.AuthenticatedMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.playpen.core.protocol.Protocol.AuthenticatedMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.playpen.core.protocol.AuthenticatedMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.playpen.core.protocol.AuthenticatedMessage)
        io.playpen.core.protocol.Protocol.AuthenticatedMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.playpen.core.protocol.Protocol.internal_static_io_playpen_core_protocol_AuthenticatedMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.playpen.core.protocol.Protocol.internal_static_io_playpen_core_protocol_AuthenticatedMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.playpen.core.protocol.Protocol.AuthenticatedMessage.class, io.playpen.core.protocol.Protocol.AuthenticatedMessage.Builder.class);
      }

      // Construct using io.playpen.core.protocol.Protocol.AuthenticatedMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        hash_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        payload_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.playpen.core.protocol.Protocol.internal_static_io_playpen_core_protocol_AuthenticatedMessage_descriptor;
      }

      public io.playpen.core.protocol.Protocol.AuthenticatedMessage getDefaultInstanceForType() {
        return io.playpen.core.protocol.Protocol.AuthenticatedMessage.getDefaultInstance();
      }

      public io.playpen.core.protocol.Protocol.AuthenticatedMessage build() {
        io.playpen.core.protocol.Protocol.AuthenticatedMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.playpen.core.protocol.Protocol.AuthenticatedMessage buildPartial() {
        io.playpen.core.protocol.Protocol.AuthenticatedMessage result = new io.playpen.core.protocol.Protocol.AuthenticatedMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uuid_ = uuid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.hash_ = hash_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.payload_ = payload_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.playpen.core.protocol.Protocol.AuthenticatedMessage) {
          return mergeFrom((io.playpen.core.protocol.Protocol.AuthenticatedMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.playpen.core.protocol.Protocol.AuthenticatedMessage other) {
        if (other == io.playpen.core.protocol.Protocol.AuthenticatedMessage.getDefaultInstance()) return this;
        if (other.hasUuid()) {
          bitField0_ |= 0x00000001;
          uuid_ = other.uuid_;
          onChanged();
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasHash()) {
          bitField0_ |= 0x00000004;
          hash_ = other.hash_;
          onChanged();
        }
        if (other.hasPayload()) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUuid()) {
          
          return false;
        }
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasHash()) {
          
          return false;
        }
        if (!hasPayload()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.playpen.core.protocol.Protocol.AuthenticatedMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.playpen.core.protocol.Protocol.AuthenticatedMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object uuid_ = "";
      /**
       * <code>required string uuid = 1;</code>
       */
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string uuid = 1;</code>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uuid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string uuid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string uuid = 1;</code>
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string uuid = 1;</code>
       */
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <code>required string uuid = 1;</code>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uuid_ = value;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>required uint32 version = 4;</code>
       *
       * <pre>
       * VERSION IS SET IN io.playpen.core.Bootstrap
       * </pre>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 version = 4;</code>
       *
       * <pre>
       * VERSION IS SET IN io.playpen.core.Bootstrap
       * </pre>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required uint32 version = 4;</code>
       *
       * <pre>
       * VERSION IS SET IN io.playpen.core.Bootstrap
       * </pre>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000002;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 version = 4;</code>
       *
       * <pre>
       * VERSION IS SET IN io.playpen.core.Bootstrap
       * </pre>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object hash_ = "";
      /**
       * <code>required string hash = 2;</code>
       */
      public boolean hasHash() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string hash = 2;</code>
       */
      public java.lang.String getHash() {
        java.lang.Object ref = hash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            hash_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string hash = 2;</code>
       */
      public com.google.protobuf.ByteString
          getHashBytes() {
        java.lang.Object ref = hash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string hash = 2;</code>
       */
      public Builder setHash(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        hash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string hash = 2;</code>
       */
      public Builder clearHash() {
        bitField0_ = (bitField0_ & ~0x00000004);
        hash_ = getDefaultInstance().getHash();
        onChanged();
        return this;
      }
      /**
       * <code>required string hash = 2;</code>
       */
      public Builder setHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        hash_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes payload = 3;</code>
       */
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes payload = 3;</code>
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>required bytes payload = 3;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes payload = 3;</code>
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000008);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:io.playpen.core.protocol.AuthenticatedMessage)
    }

    static {
      defaultInstance = new AuthenticatedMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:io.playpen.core.protocol.AuthenticatedMessage)
  }

  public interface TransactionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.playpen.core.protocol.Transaction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required .io.playpen.core.protocol.Transaction.Mode mode = 2;</code>
     */
    boolean hasMode();
    /**
     * <code>required .io.playpen.core.protocol.Transaction.Mode mode = 2;</code>
     */
    io.playpen.core.protocol.Protocol.Transaction.Mode getMode();

    /**
     * <code>required .io.playpen.core.protocol.BaseCommand payload = 3;</code>
     */
    boolean hasPayload();
    /**
     * <code>required .io.playpen.core.protocol.BaseCommand payload = 3;</code>
     */
    io.playpen.core.protocol.Commands.BaseCommand getPayload();
    /**
     * <code>required .io.playpen.core.protocol.BaseCommand payload = 3;</code>
     */
    io.playpen.core.protocol.Commands.BaseCommandOrBuilder getPayloadOrBuilder();
  }
  /**
   * Protobuf type {@code io.playpen.core.protocol.Transaction}
   */
  public static final class Transaction extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:io.playpen.core.protocol.Transaction)
      TransactionOrBuilder {
    // Use Transaction.newBuilder() to construct.
    private Transaction(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Transaction(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Transaction defaultInstance;
    public static Transaction getDefaultInstance() {
      return defaultInstance;
    }

    public Transaction getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Transaction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              io.playpen.core.protocol.Protocol.Transaction.Mode value = io.playpen.core.protocol.Protocol.Transaction.Mode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                mode_ = value;
              }
              break;
            }
            case 26: {
              io.playpen.core.protocol.Commands.BaseCommand.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = payload_.toBuilder();
              }
              payload_ = input.readMessage(io.playpen.core.protocol.Commands.BaseCommand.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(payload_);
                payload_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.playpen.core.protocol.Protocol.internal_static_io_playpen_core_protocol_Transaction_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.playpen.core.protocol.Protocol.internal_static_io_playpen_core_protocol_Transaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.playpen.core.protocol.Protocol.Transaction.class, io.playpen.core.protocol.Protocol.Transaction.Builder.class);
    }

    public static com.google.protobuf.Parser<Transaction> PARSER =
        new com.google.protobuf.AbstractParser<Transaction>() {
      public Transaction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Transaction(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Transaction> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code io.playpen.core.protocol.Transaction.Mode}
     */
    public enum Mode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CREATE = 1;</code>
       *
       * <pre>
       * creates a transaction
       * </pre>
       */
      CREATE(0, 1),
      /**
       * <code>CONTINUE = 2;</code>
       *
       * <pre>
       * uses an existing transaction
       * </pre>
       */
      CONTINUE(1, 2),
      /**
       * <code>COMPLETE = 3;</code>
       *
       * <pre>
       * ends an existing transaction
       * </pre>
       */
      COMPLETE(2, 3),
      /**
       * <code>SINGLE = 4;</code>
       *
       * <pre>
       * creates and ends a transaction
       * </pre>
       */
      SINGLE(3, 4),
      ;

      /**
       * <code>CREATE = 1;</code>
       *
       * <pre>
       * creates a transaction
       * </pre>
       */
      public static final int CREATE_VALUE = 1;
      /**
       * <code>CONTINUE = 2;</code>
       *
       * <pre>
       * uses an existing transaction
       * </pre>
       */
      public static final int CONTINUE_VALUE = 2;
      /**
       * <code>COMPLETE = 3;</code>
       *
       * <pre>
       * ends an existing transaction
       * </pre>
       */
      public static final int COMPLETE_VALUE = 3;
      /**
       * <code>SINGLE = 4;</code>
       *
       * <pre>
       * creates and ends a transaction
       * </pre>
       */
      public static final int SINGLE_VALUE = 4;


      public final int getNumber() { return value; }

      public static Mode valueOf(int value) {
        switch (value) {
          case 1: return CREATE;
          case 2: return CONTINUE;
          case 3: return COMPLETE;
          case 4: return SINGLE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Mode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Mode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Mode>() {
              public Mode findValueByNumber(int number) {
                return Mode.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return io.playpen.core.protocol.Protocol.Transaction.getDescriptor().getEnumTypes().get(0);
      }

      private static final Mode[] VALUES = values();

      public static Mode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Mode(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:io.playpen.core.protocol.Transaction.Mode)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MODE_FIELD_NUMBER = 2;
    private io.playpen.core.protocol.Protocol.Transaction.Mode mode_;
    /**
     * <code>required .io.playpen.core.protocol.Transaction.Mode mode = 2;</code>
     */
    public boolean hasMode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .io.playpen.core.protocol.Transaction.Mode mode = 2;</code>
     */
    public io.playpen.core.protocol.Protocol.Transaction.Mode getMode() {
      return mode_;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 3;
    private io.playpen.core.protocol.Commands.BaseCommand payload_;
    /**
     * <code>required .io.playpen.core.protocol.BaseCommand payload = 3;</code>
     */
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .io.playpen.core.protocol.BaseCommand payload = 3;</code>
     */
    public io.playpen.core.protocol.Commands.BaseCommand getPayload() {
      return payload_;
    }
    /**
     * <code>required .io.playpen.core.protocol.BaseCommand payload = 3;</code>
     */
    public io.playpen.core.protocol.Commands.BaseCommandOrBuilder getPayloadOrBuilder() {
      return payload_;
    }

    private void initFields() {
      id_ = "";
      mode_ = io.playpen.core.protocol.Protocol.Transaction.Mode.CREATE;
      payload_ = io.playpen.core.protocol.Commands.BaseCommand.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPayload()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getPayload().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, mode_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, payload_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, mode_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.playpen.core.protocol.Protocol.Transaction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.playpen.core.protocol.Protocol.Transaction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.playpen.core.protocol.Protocol.Transaction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.playpen.core.protocol.Protocol.Transaction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.playpen.core.protocol.Protocol.Transaction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.playpen.core.protocol.Protocol.Transaction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.playpen.core.protocol.Protocol.Transaction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.playpen.core.protocol.Protocol.Transaction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.playpen.core.protocol.Protocol.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.playpen.core.protocol.Protocol.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.playpen.core.protocol.Protocol.Transaction prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.playpen.core.protocol.Transaction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.playpen.core.protocol.Transaction)
        io.playpen.core.protocol.Protocol.TransactionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.playpen.core.protocol.Protocol.internal_static_io_playpen_core_protocol_Transaction_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.playpen.core.protocol.Protocol.internal_static_io_playpen_core_protocol_Transaction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.playpen.core.protocol.Protocol.Transaction.class, io.playpen.core.protocol.Protocol.Transaction.Builder.class);
      }

      // Construct using io.playpen.core.protocol.Protocol.Transaction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPayloadFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        mode_ = io.playpen.core.protocol.Protocol.Transaction.Mode.CREATE;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (payloadBuilder_ == null) {
          payload_ = io.playpen.core.protocol.Commands.BaseCommand.getDefaultInstance();
        } else {
          payloadBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.playpen.core.protocol.Protocol.internal_static_io_playpen_core_protocol_Transaction_descriptor;
      }

      public io.playpen.core.protocol.Protocol.Transaction getDefaultInstanceForType() {
        return io.playpen.core.protocol.Protocol.Transaction.getDefaultInstance();
      }

      public io.playpen.core.protocol.Protocol.Transaction build() {
        io.playpen.core.protocol.Protocol.Transaction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.playpen.core.protocol.Protocol.Transaction buildPartial() {
        io.playpen.core.protocol.Protocol.Transaction result = new io.playpen.core.protocol.Protocol.Transaction(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.mode_ = mode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (payloadBuilder_ == null) {
          result.payload_ = payload_;
        } else {
          result.payload_ = payloadBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.playpen.core.protocol.Protocol.Transaction) {
          return mergeFrom((io.playpen.core.protocol.Protocol.Transaction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.playpen.core.protocol.Protocol.Transaction other) {
        if (other == io.playpen.core.protocol.Protocol.Transaction.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasMode()) {
          setMode(other.getMode());
        }
        if (other.hasPayload()) {
          mergePayload(other.getPayload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasMode()) {
          
          return false;
        }
        if (!hasPayload()) {
          
          return false;
        }
        if (!getPayload().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.playpen.core.protocol.Protocol.Transaction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.playpen.core.protocol.Protocol.Transaction) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private io.playpen.core.protocol.Protocol.Transaction.Mode mode_ = io.playpen.core.protocol.Protocol.Transaction.Mode.CREATE;
      /**
       * <code>required .io.playpen.core.protocol.Transaction.Mode mode = 2;</code>
       */
      public boolean hasMode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .io.playpen.core.protocol.Transaction.Mode mode = 2;</code>
       */
      public io.playpen.core.protocol.Protocol.Transaction.Mode getMode() {
        return mode_;
      }
      /**
       * <code>required .io.playpen.core.protocol.Transaction.Mode mode = 2;</code>
       */
      public Builder setMode(io.playpen.core.protocol.Protocol.Transaction.Mode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        mode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .io.playpen.core.protocol.Transaction.Mode mode = 2;</code>
       */
      public Builder clearMode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        mode_ = io.playpen.core.protocol.Protocol.Transaction.Mode.CREATE;
        onChanged();
        return this;
      }

      private io.playpen.core.protocol.Commands.BaseCommand payload_ = io.playpen.core.protocol.Commands.BaseCommand.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          io.playpen.core.protocol.Commands.BaseCommand, io.playpen.core.protocol.Commands.BaseCommand.Builder, io.playpen.core.protocol.Commands.BaseCommandOrBuilder> payloadBuilder_;
      /**
       * <code>required .io.playpen.core.protocol.BaseCommand payload = 3;</code>
       */
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .io.playpen.core.protocol.BaseCommand payload = 3;</code>
       */
      public io.playpen.core.protocol.Commands.BaseCommand getPayload() {
        if (payloadBuilder_ == null) {
          return payload_;
        } else {
          return payloadBuilder_.getMessage();
        }
      }
      /**
       * <code>required .io.playpen.core.protocol.BaseCommand payload = 3;</code>
       */
      public Builder setPayload(io.playpen.core.protocol.Commands.BaseCommand value) {
        if (payloadBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          payloadBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .io.playpen.core.protocol.BaseCommand payload = 3;</code>
       */
      public Builder setPayload(
          io.playpen.core.protocol.Commands.BaseCommand.Builder builderForValue) {
        if (payloadBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          payloadBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .io.playpen.core.protocol.BaseCommand payload = 3;</code>
       */
      public Builder mergePayload(io.playpen.core.protocol.Commands.BaseCommand value) {
        if (payloadBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              payload_ != io.playpen.core.protocol.Commands.BaseCommand.getDefaultInstance()) {
            payload_ =
              io.playpen.core.protocol.Commands.BaseCommand.newBuilder(payload_).mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          payloadBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .io.playpen.core.protocol.BaseCommand payload = 3;</code>
       */
      public Builder clearPayload() {
        if (payloadBuilder_ == null) {
          payload_ = io.playpen.core.protocol.Commands.BaseCommand.getDefaultInstance();
          onChanged();
        } else {
          payloadBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .io.playpen.core.protocol.BaseCommand payload = 3;</code>
       */
      public io.playpen.core.protocol.Commands.BaseCommand.Builder getPayloadBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getPayloadFieldBuilder().getBuilder();
      }
      /**
       * <code>required .io.playpen.core.protocol.BaseCommand payload = 3;</code>
       */
      public io.playpen.core.protocol.Commands.BaseCommandOrBuilder getPayloadOrBuilder() {
        if (payloadBuilder_ != null) {
          return payloadBuilder_.getMessageOrBuilder();
        } else {
          return payload_;
        }
      }
      /**
       * <code>required .io.playpen.core.protocol.BaseCommand payload = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          io.playpen.core.protocol.Commands.BaseCommand, io.playpen.core.protocol.Commands.BaseCommand.Builder, io.playpen.core.protocol.Commands.BaseCommandOrBuilder> 
          getPayloadFieldBuilder() {
        if (payloadBuilder_ == null) {
          payloadBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              io.playpen.core.protocol.Commands.BaseCommand, io.playpen.core.protocol.Commands.BaseCommand.Builder, io.playpen.core.protocol.Commands.BaseCommandOrBuilder>(
                  getPayload(),
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        return payloadBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:io.playpen.core.protocol.Transaction)
    }

    static {
      defaultInstance = new Transaction(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:io.playpen.core.protocol.Transaction)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_playpen_core_protocol_AuthenticatedMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_playpen_core_protocol_AuthenticatedMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_playpen_core_protocol_Transaction_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_playpen_core_protocol_Transaction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016protocol.proto\022\030io.playpen.core.protoc" +
      "ol\032\rcommand.proto\"T\n\024AuthenticatedMessag" +
      "e\022\014\n\004uuid\030\001 \002(\t\022\017\n\007version\030\004 \002(\r\022\014\n\004hash" +
      "\030\002 \002(\t\022\017\n\007payload\030\003 \002(\014\"\307\001\n\013Transaction\022" +
      "\n\n\002id\030\001 \002(\t\0228\n\004mode\030\002 \002(\0162*.io.playpen.c" +
      "ore.protocol.Transaction.Mode\0226\n\007payload" +
      "\030\003 \002(\0132%.io.playpen.core.protocol.BaseCo" +
      "mmand\":\n\004Mode\022\n\n\006CREATE\020\001\022\014\n\010CONTINUE\020\002\022" +
      "\014\n\010COMPLETE\020\003\022\n\n\006SINGLE\020\004B\nB\010Protocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.playpen.core.protocol.Commands.getDescriptor(),
        }, assigner);
    internal_static_io_playpen_core_protocol_AuthenticatedMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_playpen_core_protocol_AuthenticatedMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_playpen_core_protocol_AuthenticatedMessage_descriptor,
        new java.lang.String[] { "Uuid", "Version", "Hash", "Payload", });
    internal_static_io_playpen_core_protocol_Transaction_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_playpen_core_protocol_Transaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_playpen_core_protocol_Transaction_descriptor,
        new java.lang.String[] { "Id", "Mode", "Payload", });
    io.playpen.core.protocol.Commands.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
